sudo: true
dist: trusty
language: node_js
node_js:
  - '6'
before_script:
  - yarn
  - npm install -g bower
  - bower install
cache:
 directories:
   - node_modules
   - bower_components
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
